variables:
  REDIRECT_FROM: language/contract-sdk
  REDIRECT_TO: language/contract-sdk/pbc_traits/index.html
  DEPLOYABLE: 'false'

include:
- project: 'secata-public/pom/shared-ci'
  file: 'rust-lib.yml'
  ref: 'par-8738_improve_rust_pipelines'
- project: 'secata-public/pom/shared-ci'
  file: 'rust-docs.yml'
  ref: 'par-8738_improve_rust_pipelines'
- project: 'secata-public/pom/shared-ci'
  file: 'rust-coverage.yml'
  ref: 'par-8738_improve_rust_pipelines'
