variables:
  REDIRECT_FROM: language/contract-sdk
  REDIRECT_TO: language/contract-sdk/pbc_traits/index.html
  DEPLOYABLE: 'false'

include:
- project: 'secata-public/pom/shared-ci'
  file: 'rust-base.yml'
  ref: 'v.2.19.1'
- project: 'secata-public/pom/shared-ci'
  file: 'rust-docs.yml'
  ref: 'v.2.19.1'
- project: 'secata-public/pom/shared-ci'
  file: 'rust-coverage.yml'
  ref: 'v.2.19.1'
