[package]
name = "pbc_zk"
version = "16.8.0"
edition = "2021"
license = "MIT"

test = "tests"

[dependencies]
pbc_zk_macros = { path = "../pbc_zk_macros" }
once_cell = "1.18.0"

[dev-dependencies]
proptest = "1.0.0"
